services:
  - type: cron
    name: github-readme-heartbeat
    runtime: node
    plan: starter
    schedule: "30 3,9,15 * * *"
    autoDeployTrigger: off
    buildCommand: "npm install"
    startCommand: "npm run heartbeat"
    envVars:
      - key: INSTANCE_NAME
        value: render-heartbeat
      - key: GITHUB_REPOSITORY
        value: chezsan770/time-update
      - key: GITHUB_TOKEN
        sync: false
